In [1]:
import pandas as pd
import numpy as np

housing = pd.read_csv("housing.csv")
housing = housing.drop("median_house_value", axis=1)

In [2]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income ocean_proximity  
0       322.0       126.0         8.3252        NEAR BAY  
1      2401.0      1138.0         8.3014        NEAR BAY  
2       496.0       177.0         7.2574        NEAR BAY  
3       558.0       219.0         5.6431        NEAR BAY  
4       565.0       259.0         3.8462        NEAR BAY

# 处理数值属性的缺失值

In [3]:
#total_bed部分值缺失
#通过DataFrame的dropna(),drop(),和fillna()方法

#判断是否有空
#sample_incomplete_rows = housing[housing.isnull().any(axis=1)].head()
#sample_incomplete_rows

#sample_incomplete_rows.dropna(subset=["total_bedrooms"])    # option 1

#sample_incomplete_rows.drop("total_bedrooms", axis=1)       # option 2

#median = housing["total_bedrooms"].median()
#sample_incomplete_rows["total_bedrooms"].fillna(median, inplace=True) # option 3
#sample_incomplete_rows


In [4]:
#Scikit-Learn提供： imputer，使用中位数填充缺失值
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")
#中位数只能在数值属性上计算，创建没有文本属性的数据副本
housing_num = housing.drop("ocean_proximity", axis=1)
#使用fit方法将imputer实例适配到训练集
imputer.fit(housing_num)

SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='median', verbose=0)

In [5]:
imputer.statistics_

array([-118.49  ,   34.26  ,   29.    , 2127.    ,  435.    , 1166.    ,
        409.    ,    3.5348])

In [6]:
housing_num.median()#.values

longitude             -118.4900
latitude                34.2600
housing_median_age      29.0000
total_rooms           2127.0000
total_bedrooms         435.0000
population            1166.0000
households             409.0000
median_income            3.5348
dtype: float64

In [7]:
#使用“训练有素”的imputer将缺失值替换成中位数完成训练集转换
X = imputer.transform(housing_num)

In [8]:
#结果是一个包含转换后特征的Numpy数组
X[0]

array([-122.23  ,   37.88  ,   41.    ,  880.    ,  129.    ,  322.    ,
        126.    ,    8.3252])

In [9]:
#如果想将Numpy数组放回DataFrame也很简单
housing_str = pd.DataFrame(X, columns=housing_num.columns)

In [10]:
housing_str.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  
0       322.0       126.0         8.3252  
1      2401.0      1138.0         8.3014  
2       496.0       177.0         7.2574  
3       558.0       219.0         5.6431  
4       565.0       259.0         3.8462

# 处理文本和分类属性

In [11]:
housing_cat = housing[['ocean_proximity']].copy()
housing_num = housing.drop('ocean_proximity', axis=1)

In [12]:
#将文本标签转化为数字的转换器  LabelEncoder，但是换成 OrdinalEncoder 
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded[:10]

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.]])

In [13]:
# housing_cat = housing[['ocean_proximity']]
# housing_cat.head(10)
#将数值分类转化为one-hot的转换器  OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder(sparse=False)
#housing_cat1 = housing_cat.values.reshape(1, -1)
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
# housing_cat_1hot.toarray()#转化为numpy矩阵
#或者直接用sparse=False来生成Numpy矩阵
# cat_encoder = OneHotEncoder(sparse=False)
# housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
# housing_cat_1hot#显示one-hot举着
#cat_encoder.categories_#显示索引对应文本类别

In [14]:
housing_cat_1hot    #如果sparse=True为稀疏矩阵scipy,在.toarray()转Numpy矩阵

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [15]:
cat_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [16]:
#老版使用LabelBinarizer
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()

In [17]:
housing_cat_1hot = encoder.fit_transform(housing_cat)
housing_cat_1hot

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       ...,
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]])

# 自定义转换器

In [18]:
#增加三个属性
from sklearn.base import BaseEstimator, TransformerMixin

# column index
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [19]:
housing_extra_attribs = pd.DataFrame(
    housing_extra_attribs,
    columns=list(housing.columns)+["rooms_per_household", "population_per_household"])
housing_extra_attribs.head()

longitude latitude housing_median_age total_rooms total_bedrooms population  \
0   -122.23    37.88                 41         880            129        322   
1   -122.22    37.86                 21        7099           1106       2401   
2   -122.24    37.85                 52        1467            190        496   
3   -122.25    37.85                 52        1274            235        558   
4   -122.25    37.85                 52        1627            280        565   

  households median_income ocean_proximity rooms_per_household  \
0        126        8.3252        NEAR BAY             6.98413   
1       1138        8.3014        NEAR BAY             6.23814   
2        177        7.2574        NEAR BAY             8.28814   
3        219        5.6431        NEAR BAY             5.81735   
4        259        3.8462        NEAR BAY             6.28185   

  population_per_household  
0                  2.55556  
1                  2.10984  
2                  2.80226  
3                  2.54795  
4                  2.18147

# 使用转换流水线

## 对数值型

In [20]:
#对数值型数据，先处理缺省值，然后增加三属性，最后特征缩放
#StandardScaler()特征缩放，标准化
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

housing_num_tr = num_pipeline.fit_transform(housing_num)

In [33]:
housing_num_tr.shape

(20640, 11)

In [21]:
housing_num_tr

array([[-1.32783522,  1.05254828,  0.98214266, ...,  0.62855945,
        -0.04959654, -1.02998783],
       [-1.32284391,  1.04318455, -0.60701891, ...,  0.32704136,
        -0.09251223, -0.8888972 ],
       [-1.33282653,  1.03850269,  1.85618152, ...,  1.15562047,
        -0.02584253, -1.29168566],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.09031802,
        -0.0717345 ,  0.02113407],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.04021111,
        -0.09122515,  0.09346655],
       [-0.83369581,  1.75014627, -1.00430931, ..., -0.07044252,
        -0.04368215,  0.11327519]])

## 一条完整的处理数值和分类属性的流水线

### 新版构建完整的数值和文本处理的流水线

In [22]:
from sklearn.compose import ColumnTransformer
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing)

In [34]:
housing_prepared.shape

(20640, 16)

In [23]:
housing_prepared

array([[-1.32783522,  1.05254828,  0.98214266, ...,  0.        ,
         1.        ,  0.        ],
       [-1.32284391,  1.04318455, -0.60701891, ...,  0.        ,
         1.        ,  0.        ],
       [-1.33282653,  1.03850269,  1.85618152, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ...,  0.        ,
         0.        ,  0.        ],
       [-0.87362627,  1.77823747, -0.84539315, ...,  0.        ,
         0.        ,  0.        ],
       [-0.83369581,  1.75014627, -1.00430931, ...,  0.        ,
         0.        ,  0.        ]])

In [24]:
housing_prepared.shape

(20640, 16)

## 旧版

In [25]:
#Scikit-Learn中没有可以用来处理Pandas DataFrame的，编写一个简单的自定义转换器
#旧版就是Pipline里手动喂values
#简单来说就是数值型的喂给数值型，文本型喂给文本型

In [26]:
from sklearn.base import BaseEstimator, TransformerMixin

# Create a class to select numerical or categorical columns 
class OldDataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [27]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

old_num_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(num_attribs)),
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

old_cat_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(cat_attribs)),
        ('cat_encoder', OneHotEncoder(sparse=False)),
    ])

In [28]:
from sklearn.pipeline import FeatureUnion

old_full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", old_num_pipeline),
        ("cat_pipeline", old_cat_pipeline),
    ])

In [29]:
old_housing_prepared = old_full_pipeline.fit_transform(housing)
old_housing_prepared

array([[-1.32783522,  1.05254828,  0.98214266, ...,  0.        ,
         1.        ,  0.        ],
       [-1.32284391,  1.04318455, -0.60701891, ...,  0.        ,
         1.        ,  0.        ],
       [-1.33282653,  1.03850269,  1.85618152, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ...,  0.        ,
         0.        ,  0.        ],
       [-0.87362627,  1.77823747, -0.84539315, ...,  0.        ,
         0.        ,  0.        ],
       [-0.83369581,  1.75014627, -1.00430931, ...,  0.        ,
         0.        ,  0.        ]])

In [31]:
housing.shape

(20640, 9)

In [32]:
old_housing_prepared.shape

(20640, 16)

In [32]:
np.allclose(housing_prepared, old_housing_prepared)

True